### ISSUE TITLE
Vulkano-win Cargo.toml bug [FIXED]

### ISSUE THREAD

**Issue by zipper97412** [tomaka/vulkano#447]
Hi here is a strange bug (probably with cargo)
I want to run a copy of triangle.rs in my project, here is my cargo.toml:
```toml
[package]
name = "specs-test"
version = "0.1.0"
authors = ["MyNameHere"]
build = "build.rs"

[dependencies]
specs = {git = "https://github.com/slide-rs/specs.git"}
vulkano = {git = "https://github.com/tomaka/vulkano.git"}
vulkano-win = {git = "https://github.com/tomaka/vulkano.git"}
winit = "0.5.2"

[build-dependencies]
vk-sys = {git = "https://github.com/tomaka/vulkano.git"}
vulkano-shaders = {git = "https://github.com/tomaka/vulkano.git"}
```
I copied the build.rs, the shadders, and i changed the path of the shaders in build.rs and triangle.rs
everything should be fine but here is how rustc insult me:

```
error[E0433]: failed to resolve. Use of undeclared type or module `WindowBuilder`
  --> src\bin\test.rs:39:18
   |
39 |     let window = WindowBuilder::new().build_vk_surface(&instance).unwrap();
   |                  ^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `WindowBuilder`

error: aborting due to 3 previous errors
```
`use vulkano_win::VkSurfaceBuild;` is here.

Now I will show you how i fixed this:
I copied all the vulkano repository in my project and changed `{git = "https://github.com/slide-rs/specs.git"}` to `{path = "vulkano/the_crate_name_here"}` for all my vulkano dependencies and it worked.
But this is ugly and the git method should work.
Maybe I should post this in the cargo repo?
